# Generated by Django 5.2.7 on 2025-11-17 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configrevision_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='hash',
            field=models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='길이는 16진수 64자여야 합니다.', regex='^[0-9a-f]{64}$')]),
        ),
    ]
